require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
